obj-$(CONFIG_TUSB422)	+= tusb422_linux.o
obj-$(CONFIG_TUSB422)	+= tusb422_common.o
obj-$(CONFIG_TUSB422)	+= tusb422.o
obj-$(CONFIG_TUSB422)	+= tcpci.o
obj-$(CONFIG_TUSB422)	+= tcpm.o
obj-$(CONFIG_TUSB422)	+= usb_pd_policy_engine.o
obj-$(CONFIG_TUSB422)	+= usb_pd_policy_manager.o
obj-$(CONFIG_TUSB422)	+= usb_pd_protocol.o
